### PR TITLE
[composer] add 1.0 alias to dev master.

### PR DESCRIPTION
**Pull request by makasim**

### CODE REVIEW

**Comment by Ph3nol** [comment]
Thanks! :)

**Comment by makasim** [comment]
Oh, that was fast. Thank you too.

**Comment by makasim** [comment]
@Ph3nol is packagist update automatically?

**Comment by Ph3nol** [comment]
Might be done.

**Comment by makasim** [comment]
could you please release a minor version. It could not resolve package version without it

**Comment by Ph3nol** [comment]
Package last update from Packagist: 2013-11-18 12:59 UTC MIT. Good, isn't it?

**Pull request merged**
